# Generated by Django 4.2.4 on 2023-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=40, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('ConfirmPassword', models.CharField(blank=True, max_length=30, null=True)),
                ('SecurityCode', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
